apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo-project
  name: demo-project-service
spec:
  selector:
    app: demo-project
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30080
